@extends('layouts.admin')

@section('title', 'Reports & Financial Analytics')

@section('content')
<div class="row align-items-center mb-4 d-print-none">
    <div class="col-md-7">
        <h1 class="h3 fw-bold mb-1">Reports & Analytics</h1>
        <p class="text-muted mb-0">Detailed operational, financial, and occupancy summaries for your boarding house.</p>
    </div>
    <div class="col-md-5 text-md-end mt-3 mt-md-0">
        <button type="button" onclick="window.print()" class="btn btn-outline-secondary me-2">
            <i class="bi bi-printer me-1"></i> Print / Export PDF
        </button>
    </div>
</div>

<!-- Print Header (Visible only when printing) -->
<div class="d-none d-print-block mb-4 text-center">
    <h2 class="fw-bold">INTEGRATED BOARDING HOUSE MANAGEMENT SYSTEM</h2>
    <h4 class="text-uppercase text-secondary">
        @if($type === 'collections')
            Monthly Rent Collections Report - {{ $monthName }}
        @elseif($type === 'outstanding')
            Outstanding & Overdue Rent Report - {{ $monthName }}
        @elseif($type === 'occupancy')
            Room Occupancy & Revenue Yield Report
        @elseif($type === 'tenants')
            Active Tenant Directory
        @elseif($type === 'maintenance')
            Maintenance Operations Report - {{ $monthName }}
        @endif
    </h4>
    <p class="small text-muted">Generated by Admin on {{ now()->format('F d, Y h:i A') }}</p>
    <hr>
</div>

<!-- Report Navigation Tabs & Filters (Hidden when printing) -->
<div class="card border-0 shadow-sm mb-4 d-print-none">
    <div class="card-body">
        <div class="row g-3 align-items-center">
            <div class="col-lg-7">
                <div class="status-pill-scroll-container pb-1" role="group">
                    <a href="{{ route('admin.reports.index', ['type' => 'collections', 'month' => $month, 'year' => $year]) }}" 
                       class="btn btn-sm {{ $type === 'collections' ? 'btn-primary' : 'btn-outline-primary' }} rounded-pill px-3">
                        <i class="bi bi-cash-stack me-1"></i> Collections
                    </a>
                    <a href="{{ route('admin.reports.index', ['type' => 'outstanding', 'month' => $month, 'year' => $year]) }}" 
                       class="btn btn-sm {{ $type === 'outstanding' ? 'btn-primary' : 'btn-outline-primary' }} rounded-pill px-3">
                        <i class="bi bi-exclamation-triangle me-1"></i> Outstanding
                    </a>
                    <a href="{{ route('admin.reports.index', ['type' => 'occupancy', 'month' => $month, 'year' => $year]) }}" 
                       class="btn btn-sm {{ $type === 'occupancy' ? 'btn-primary' : 'btn-outline-primary' }} rounded-pill px-3">
                        <i class="bi bi-door-open me-1"></i> Occupancy
                    </a>
                    <a href="{{ route('admin.reports.index', ['type' => 'tenants', 'month' => $month, 'year' => $year]) }}" 
                       class="btn btn-sm {{ $type === 'tenants' ? 'btn-primary' : 'btn-outline-primary' }} rounded-pill px-3">
                        <i class="bi bi-people me-1"></i> Tenants
                    </a>
                    <a href="{{ route('admin.reports.index', ['type' => 'maintenance', 'month' => $month, 'year' => $year]) }}" 
                       class="btn btn-sm {{ $type === 'maintenance' ? 'btn-primary' : 'btn-outline-primary' }} rounded-pill px-3">
                        <i class="bi bi-tools me-1"></i> Maintenance
                    </a>
                </div>
            </div>

            @if(in_array($type, ['collections', 'outstanding', 'maintenance']))
            <div class="col-lg-5">
                <form action="{{ route('admin.reports.index') }}" method="GET" class="d-flex gap-2 justify-content-lg-end">
                    <input type="hidden" name="type" value="{{ $type }}">
                    <select name="month" class="form-select form-select-sm" style="max-width: 150px;">
                        @for($m = 1; $m <= 12; $m++)
                            <option value="{{ $m }}" {{ $month == $m ? 'selected' : '' }}>
                                {{ DateTime::createFromFormat('!m', $m)->format('F') }}
                            </option>
                        @endfor
                    </select>
                    <select name="year" class="form-select form-select-sm" style="max-width: 110px;">
                        @for($y = now()->year - 2; $y <= now()->year + 1; $y++)
                            <option value="{{ $y }}" {{ $year == $y ? 'selected' : '' }}>
                                {{ $y }}
                            </option>
                        @endfor
                    </select>
                    <button type="submit" class="btn btn-sm btn-primary">Filter</button>
                </form>
            </div>
            @endif
        </div>
    </div>
</div>

{{-- 1. COLLECTIONS REPORT --}}
@if($type === 'collections')
<div class="row g-3 mb-4">
    <div class="col-sm-6 col-lg-3">
        <div class="card border-0 shadow-sm">
            <div class="card-body">
                <span class="text-muted small fw-semibold text-uppercase">Total Collected</span>
                <h3 class="fw-bold text-success mt-1 mb-0">₱{{ number_format($totalCollected, 2) }}</h3>
                <small class="text-muted">{{ $payments->count() }} Verified Transactions</small>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-3">
        <div class="card border-0 shadow-sm">
            <div class="card-body">
                <span class="text-muted small fw-semibold text-uppercase">Cash Collections</span>
                <h3 class="fw-bold text-primary mt-1 mb-0">₱{{ number_format($totalCash, 2) }}</h3>
                <small class="text-muted">{{ $cashCount }} Transactions</small>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-3">
        <div class="card border-0 shadow-sm">
            <div class="card-body">
                <span class="text-muted small fw-semibold text-uppercase">GCash Collections</span>
                <h3 class="fw-bold text-info mt-1 mb-0">₱{{ number_format($totalGcash, 2) }}</h3>
                <small class="text-muted">{{ $gcashCount }} Transactions</small>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-3">
        <div class="card border-0 shadow-sm">
            <div class="card-body">
                <span class="text-muted small fw-semibold text-uppercase">Report Period</span>
                <h4 class="fw-bold mt-1 mb-0">{{ $monthName }}</h4>
                <small class="text-muted">Verified Payments Only</small>
            </div>
        </div>
    </div>
</div>

<div class="card border-0 shadow-sm">
    <div class="card-header bg-transparent py-3">
        <h5 class="fw-bold mb-0">Verified Payments - {{ $monthName }}</h5>
    </div>
    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-hover align-middle mb-0">
                <thead class="table-light">
                    <tr>
                        <th>Receipt #</th>
                        <th>Tenant</th>
                        <th>Room</th>
                        <th>Billing Cycle</th>
                        <th>Payment Date</th>
                        <th>Method</th>
                        <th>Reference / Notes</th>
                        <th class="text-end">Amount</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($payments as $payment)
                    <tr>
                        <td class="fw-semibold text-primary">#REC-{{ str_pad($payment->id, 5, '0', STR_PAD_LEFT) }}</td>
                        <td>
                            <div class="fw-semibold">{{ $payment->tenant->user->name ?? 'N/A' }}</div>
                            <small class="text-muted">{{ $payment->tenant->user->email ?? '' }}</small>
                        </td>
                        <td>{{ $payment->room->room_number ?? 'N/A' }}</td>
                        <td>{{ $payment->billing_period }}</td>
                        <td>{{ $payment->payment_date ? $payment->payment_date->format('M d, Y') : 'N/A' }}</td>
                        <td>
                            @if($payment->payment_method === 'cash')
                                <span class="badge bg-success-subtle text-success border border-success-subtle">Cash</span>
                            @else
                                <span class="badge bg-info-subtle text-info border border-info-subtle">GCash</span>
                            @endif
                        </td>
                        <td>
                            <small class="text-muted">{{ $payment->gcash_reference ?: ($payment->notes ?: '—') }}</small>
                        </td>
                        <td class="text-end fw-bold text-success">₱{{ number_format($payment->amount, 2) }}</td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="8" class="text-center py-5 text-muted">
                            <i class="bi bi-inbox fs-1 d-block mb-2"></i>
                            No verified payments found for {{ $monthName }}.
                        </td>
                    </tr>
                    @endforelse
                </tbody>
                @if($payments->isNotEmpty())
                <tfoot class="table-light">
                    <tr>
                        <td colspan="7" class="fw-bold text-end">TOTAL COLLECTED:</td>
                        <td class="text-end fw-bold text-success fs-6">₱{{ number_format($totalCollected, 2) }}</td>
                    </tr>
                </tfoot>
                @endif
            </table>
        </div>
    </div>
</div>

{{-- 2. OUTSTANDING RENT REPORT --}}
@elseif($type === 'outstanding')
<div class="row g-3 mb-4">
    <div class="col-sm-6 col-lg-4">
        <div class="card border-0 shadow-sm">
            <div class="card-body">
                <span class="text-muted small fw-semibold text-uppercase">Total Outstanding</span>
                <h3 class="fw-bold text-danger mt-1 mb-0">₱{{ number_format($totalOutstanding, 2) }}</h3>
                <small class="text-muted">Uncollected for {{ $monthName }}</small>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-4">
        <div class="card border-0 shadow-sm">
            <div class="card-body">
                <span class="text-muted small fw-semibold text-uppercase">Overdue Tenants</span>
                <h3 class="fw-bold text-danger mt-1 mb-0">{{ $overdueCount }}</h3>
                <small class="text-muted">Past monthly due date</small>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-4">
        <div class="card border-0 shadow-sm">
            <div class="card-body">
                <span class="text-muted small fw-semibold text-uppercase">Unsettled Accounts</span>
                <h3 class="fw-bold text-warning mt-1 mb-0">{{ count($outstandingList) }}</h3>
                <small class="text-muted">Tenants pending payment</small>
            </div>
        </div>
    </div>
</div>

<div class="card border-0 shadow-sm">
    <div class="card-header bg-transparent py-3">
        <h5 class="fw-bold mb-0">Outstanding Accounts - {{ $monthName }}</h5>
    </div>
    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-hover align-middle mb-0">
                <thead class="table-light">
                    <tr>
                        <th>Tenant</th>
                        <th>Contact Number</th>
                        <th>Room</th>
                        <th>Monthly Rent</th>
                        <th>Due Date</th>
                        <th>Status</th>
                        <th class="d-print-none text-end">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($outstandingList as $item)
                    <tr>
                        <td>
                            <div class="fw-semibold">{{ $item['tenant']->user->name }}</div>
                            <small class="text-muted">{{ $item['tenant']->user->email }}</small>
                        </td>
                        <td>{{ $item['tenant']->user->contact_number ?? 'N/A' }}</td>
                        <td>
                            <span class="badge bg-secondary-subtle text-secondary">
                                Room {{ $item['room']->room_number ?? 'N/A' }}
                            </span>
                        </td>
                        <td class="fw-bold text-danger">
                            ₱{{ number_format($item['amount'], 2) }}
                            @if(isset($item['paid_amount']) && $item['paid_amount'] > 0)
                                <div class="small text-success fw-normal" style="font-size: 0.72rem;"><i class="bi bi-pie-chart"></i> Paid: ₱{{ number_format($item['paid_amount'], 2) }}</div>
                            @endif
                        </td>
                        <td>{{ $item['due_date']->format('M d, Y') }}</td>
                        <td>
                            @if($item['has_pending'])
                                <span class="badge bg-warning text-dark">
                                    <i class="bi bi-hourglass-split me-1"></i> Waiting for Approval
                                </span>
                            @elseif(isset($item['paid_amount']) && $item['paid_amount'] > 0)
                                <span class="badge bg-warning text-dark border border-warning">
                                    <i class="bi bi-pie-chart-fill me-1"></i> Partially Paid
                                </span>
                            @elseif($item['is_overdue'])
                                <span class="badge bg-danger text-white">
                                    <i class="bi bi-exclamation-triangle me-1"></i> Overdue
                                </span>
                            @else
                                <span class="badge bg-info-subtle text-info border border-info-subtle">
                                    <i class="bi bi-calendar-event me-1"></i> Pending Payment
                                </span>
                            @endif
                        </td>
                        <td class="d-print-none text-end">
                            <a href="{{ route('admin.payments.create', ['tenant_id' => $item['tenant']->id, 'billing_month' => $month, 'billing_year' => $year]) }}" class="btn btn-sm btn-outline-success">
                                <i class="bi bi-cash me-1"></i> Record Cash
                            </a>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="7" class="text-center py-5 text-muted">
                            <i class="bi bi-check-circle-fill text-success fs-1 d-block mb-2"></i>
                            All active tenants have settled their rent for {{ $monthName }}!
                        </td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>

{{-- 3. OCCUPANCY REPORT --}}
@elseif($type === 'occupancy')
<div class="row g-3 mb-4">
    <div class="col-sm-6 col-lg-3">
        <div class="card border-0 shadow-sm">
            <div class="card-body">
                <span class="text-muted small fw-semibold text-uppercase">Total Capacity</span>
                <h3 class="fw-bold mt-1 mb-0">{{ $totalCapacity }} Slots</h3>
                <small class="text-muted">Across {{ $totalRooms }} Rooms</small>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-3">
        <div class="card border-0 shadow-sm">
            <div class="card-body">
                <span class="text-muted small fw-semibold text-uppercase">Occupied Slots</span>
                <h3 class="fw-bold text-primary mt-1 mb-0">{{ $occupiedSlots }} Tenants</h3>
                <small class="text-muted">{{ $occupancyRate }}% Occupancy Rate</small>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-3">
        <div class="card border-0 shadow-sm">
            <div class="card-body">
                <span class="text-muted small fw-semibold text-uppercase">Available Slots</span>
                <h3 class="fw-bold text-success mt-1 mb-0">{{ $availableSlots }} Slots</h3>
                <small class="text-muted">Ready for new tenants</small>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-3">
        <div class="card border-0 shadow-sm">
            <div class="card-body">
                <span class="text-muted small fw-semibold text-uppercase">Monthly Yield</span>
                <h3 class="fw-bold text-success mt-1 mb-0">₱{{ number_format($currentMonthlyRevenue, 2) }}</h3>
                <small class="text-muted">Potential: ₱{{ number_format($potentialMonthlyRevenue, 2) }}</small>
            </div>
        </div>
    </div>
</div>

<div class="card border-0 shadow-sm">
    <div class="card-header bg-transparent py-3">
        <h5 class="fw-bold mb-0">Room Inventory & Occupancy Status</h5>
    </div>
    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-hover align-middle mb-0">
                <thead class="table-light">
                    <tr>
                        <th>Room Number</th>
                        <th>Type / Floor</th>
                        <th>Capacity</th>
                        <th>Occupied</th>
                        <th>Available Slots</th>
                        <th>Monthly Rent</th>
                        <th>Current Occupants (Admin Only)</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($rooms as $room)
                    <tr>
                        <td class="fw-bold">Room {{ $room->room_number }}</td>
                        <td>{{ $room->room_type }} (Floor {{ $room->floor }})</td>
                        <td>{{ $room->capacity }}</td>
                        <td>{{ $room->activeTenants->count() }}</td>
                        <td>
                            @php $free = max(0, $room->capacity - $room->activeTenants->count()); @endphp
                            <span class="badge {{ $free > 0 ? 'bg-success-subtle text-success' : 'bg-secondary-subtle text-secondary' }}">
                                {{ $free }} free
                            </span>
                        </td>
                        <td class="fw-semibold">₱{{ number_format($room->monthly_rent, 2) }}</td>
                        <td>
                            @if($room->activeTenants->isNotEmpty())
                                <div class="d-flex flex-wrap gap-1">
                                    @foreach($room->activeTenants as $tenant)
                                        <span class="badge bg-light text-dark border">{{ $tenant->user->name ?? 'Tenant' }}</span>
                                    @endforeach
                                </div>
                            @else
                                <span class="text-muted small">No current occupants</span>
                            @endif
                        </td>
                        <td>
                            @if($room->is_available)
                                <span class="badge bg-success-subtle text-success">Available</span>
                            @else
                                <span class="badge bg-danger-subtle text-danger">Not Available</span>
                            @endif
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

{{-- 4. TENANTS REPORT --}}
@elseif($type === 'tenants')
<div class="card border-0 shadow-sm">
    <div class="card-header bg-transparent py-3 d-flex justify-content-between align-items-center">
        <h5 class="fw-bold mb-0">Active Tenants Directory ({{ $tenants->count() }} Total)</h5>
    </div>
    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-hover align-middle mb-0">
                <thead class="table-light">
                    <tr>
                        <th>Tenant Code</th>
                        <th>Full Name</th>
                        <th>Email & Contact</th>
                        <th>Assigned Room</th>
                        <th>Monthly Rent</th>
                        <th>Move-In Date</th>
                        <th>Emergency Contact</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($tenants as $tenant)
                    <tr>
                        <td class="fw-semibold text-primary">{{ $tenant->tenant_code }}</td>
                        <td class="fw-bold">{{ $tenant->user->name }}</td>
                        <td>
                            <div>{{ $tenant->user->email }}</div>
                            <small class="text-muted">{{ $tenant->user->contact_number ?? 'No contact' }}</small>
                        </td>
                        <td>
                            @if($tenant->room)
                                <span class="badge bg-primary-subtle text-primary">
                                    Room {{ $tenant->room->room_number }} ({{ $tenant->room->room_type }})
                                </span>
                            @else
                                <span class="badge bg-warning-subtle text-warning">Unassigned</span>
                            @endif
                        </td>
                        <td class="fw-semibold">
                            ₱{{ number_format($tenant->room ? $tenant->room->monthly_rent : 0, 2) }}
                        </td>
                        <td>{{ $tenant->move_in_date ? $tenant->move_in_date->format('M d, Y') : 'N/A' }}</td>
                        <td>
                            <small>
                                <strong>{{ $tenant->emergency_contact_name ?? '—' }}</strong><br>
                                <span class="text-muted">{{ $tenant->emergency_contact_number ?? '' }}</span>
                            </small>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="7" class="text-center py-5 text-muted">No active tenants found.</td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>

{{-- 5. MAINTENANCE REPORT --}}
@elseif($type === 'maintenance')
<div class="row g-3 mb-4">
    <div class="col-sm-6 col-lg-3">
        <div class="card border-0 shadow-sm">
            <div class="card-body">
                <span class="text-muted small fw-semibold text-uppercase">Total Tickets</span>
                <h3 class="fw-bold mt-1 mb-0">{{ $totalRequests }}</h3>
                <small class="text-muted">{{ $monthName }}</small>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-3">
        <div class="card border-0 shadow-sm">
            <div class="card-body">
                <span class="text-muted small fw-semibold text-uppercase">Pending</span>
                <h3 class="fw-bold text-warning mt-1 mb-0">{{ $pendingRequests }}</h3>
                <small class="text-muted">Awaiting action</small>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-3">
        <div class="card border-0 shadow-sm">
            <div class="card-body">
                <span class="text-muted small fw-semibold text-uppercase">In Progress</span>
                <h3 class="fw-bold text-info mt-1 mb-0">{{ $inProgressRequests }}</h3>
                <small class="text-muted">Under repair</small>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-lg-3">
        <div class="card border-0 shadow-sm">
            <div class="card-body">
                <span class="text-muted small fw-semibold text-uppercase">Resolved</span>
                <h3 class="fw-bold text-success mt-1 mb-0">{{ $resolvedRequests }}</h3>
                <small class="text-muted">Completed repairs</small>
            </div>
        </div>
    </div>
</div>

<div class="card border-0 shadow-sm">
    <div class="card-header bg-transparent py-3">
        <h5 class="fw-bold mb-0">Maintenance Log - {{ $monthName }}</h5>
    </div>
    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-hover align-middle mb-0">
                <thead class="table-light">
                    <tr>
                        <th>Ticket #</th>
                        <th>Room</th>
                        <th>Tenant</th>
                        <th>Issue Title</th>
                        <th>Priority</th>
                        <th>Assigned Staff</th>
                        <th>Status</th>
                        <th>Submitted</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($requests as $req)
                    <tr>
                        <td class="fw-semibold text-primary">#MNT-{{ str_pad($req->id, 5, '0', STR_PAD_LEFT) }}</td>
                        <td>Room {{ $req->room->room_number ?? 'N/A' }}</td>
                        <td>{{ $req->tenant->user->name ?? 'N/A' }}</td>
                        <td class="fw-semibold">{{ $req->title }}</td>
                        <td>
                            @if($req->priority === 'urgent')
                                <span class="badge bg-danger">Urgent</span>
                            @elseif($req->priority === 'high')
                                <span class="badge bg-warning text-dark">High</span>
                            @elseif($req->priority === 'medium')
                                <span class="badge bg-info text-dark">Medium</span>
                            @else
                                <span class="badge bg-secondary">Low</span>
                            @endif
                        </td>
                        <td>{{ $req->assigned_to ?? 'Unassigned' }}</td>
                        <td>
                            @if($req->status === 'resolved')
                                <span class="badge bg-success-subtle text-success border border-success-subtle">Resolved</span>
                            @elseif($req->status === 'in_progress')
                                <span class="badge bg-info-subtle text-info border border-info-subtle">In Progress</span>
                            @elseif($req->status === 'rejected')
                                <span class="badge bg-danger-subtle text-danger border border-danger-subtle">Rejected</span>
                            @else
                                <span class="badge bg-warning-subtle text-warning border border-warning-subtle">Pending</span>
                            @endif
                        </td>
                        <td>{{ $req->created_at->format('M d, Y') }}</td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="8" class="text-center py-5 text-muted">No maintenance requests found for {{ $monthName }}.</td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>
@endif

@endsection
